name: ci pipeline

on:
  push:
    branches:
      - feat/add_pipeline_build_and_push_container_image
  pull_request:
    branches:
      - dev

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: set short commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      version-tag: ${{ steps.vars.outputs.sha_short }}

  build-pipeline:
    needs: get-version
    permissions:
      packages: write
    uses: warapong-pj/reusable-workflows/.github/workflows/build_and_push_container_image.yaml@feat/add_build_and_push_pipeline
    with:
      registry: ghcr.io/${{ github.actor }}
      username: ${{ github.actor }}
      application: sample-app
      version: ${{ needs.get-version.outputs.version-tag }}
    secrets:
      password: ${{ secrets.GITHUB_TOKEN }}