name: sast pipeline

on:
  push:
    branches:
      - feat/add_pipeline_build_and_push_container_image

jobs:
  sast-pipeline:
    uses: warapong-pj/reusable-workflows/.github/workflows/sast_scan.yaml@feat/add_sast_scan_pipeline